### ISSUE TITLE
menu mobile not working

### ISSUE THREAD

**Issue by lueck-it** [abhilive/angularJs-startbootstrap-modern-business#1]
Hi,
thank you for sending me the link to your angularJS-startbootstrap-modern-business-version.
The slider works! Fine! 
Do you have an idea why your mobile-menue doesn't work?
Thank you. With best regards 
Tim

**Comment by abhilive** [comment]
Hi Tim,

Please look this now. I fixed that mobile menu issue. Thanks

**Comment by lueck-it** [comment]
Thank you. It works! :)
